# This workflow will automatically upload a binary artifact when a release/tag  is created
name: Build and upload binary

on:
  # allow to build manually
  workflow_dispatch:
  # build automatically when pushing a tag
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows builds
          # - os: windows-latest
          #   target: x86_64-windows-gnu
          #   suffix: windows_amd64
          # - os: windows-latest
          #   target: aarch64-windows-gnu
          #   suffix: windows_arm64
          #   cpu: arm64
          # Linux builds
          - os: ubuntu-latest
            target: aarch64-linux-gnu
            suffix: linux_arm64
            cpu: arm64
          - os: ubuntu-latest
            target: x86_64-linux-gnu
            suffix: linux_amd64
            cpu: amd64

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.11.0
      - name: Install dependencies
        run: |
          nimble install -y zigcc
      - name: Build binary
        run: nimble -y build -d:zig.target="${{ matrix.target }}" --cpu:"${{ matrix.cpu }}" --out:bin/choosenim-${{ github.ref }}_${{ matrix.suffix }}

      - name: Upload binaries to release/tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          tag: ${{ github.ref }}
          file: bin/choosenim-${{ github.ref }}_${{ matrix.suffix }}
