# This workflow will automatically upload a binary artifact when a release/tag  is created
name: Build and upload binary

on:
  # allow to build manually
  workflow_dispatch:
  # build automatically when pushing a tag
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install zig
        run: sudo apt update && sudo apt install zig
      - name: Build binary
        run: |
          nimble -y release

      - name: Upload binaries to release/tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          tag: ${{ github.ref }}
          file_glob: true
          file: bin/*
